#!/bin/bash
# by fuldaros
clear
e="\x1b[";c=$e"39;49;00m";y=$e"93;01m";cy=$e"96;01m";r=$e"1;91m";g=$e"92;01m";m=$e"95;01m";
conf=$(sed -n 6p make.prop);
arch=$(sed -n 4p make.prop);
echo -e "
$cy****************************************************
$cy*           Automatic kernel builder v"$ver"          *
$cy*                   by fuldaros                    *
$cy****************************************************
$y";     
set -e 
./tools/clean.sh
rm -f gen.info
mkdir out
mkdir outkernel
mkdir outzip
export ARCH="$arch"
stamp=$(date +"%H:%M:%S %Y.%m.%d");
echo "generated by fuldaros's script on "$stamp" " > gen.info
cd sources
make O=../out/paperplane "$conf"
cd ../
./build.sh
